name        = "Béopy"
name8       = "beopy"
locale      = "fr"
variant     = "beopy"
description = "French (Béopy)"
author      = "Beri"
url         = "https://bepo.fr/wiki/Utilisateur:Beri"
geometry    = "ERGO"
version     = "1.0.0"

base = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆ #   ┃ 1   │ 2   │ 3   │ 4   │ 5   ┃ 6   │ 7   │ 8   │ 9   │ 0   ┃ °   ┆ `   ┆
┆ $   ┃ "   │ «   │ »   │ (   │ )   ┃ @   │ +   │ -   │ /   │ *   ┃ =   ┆ %   ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ B   │ É   │ O   │ P   │ Y   ┃ !   │ V   │ D   │ L   │ J   ┃ K   ┆ Z   ┆
·     ┃     │     │     │     │     ┃     │     │     │     │     ┃     ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ A   │ U   │ E   │ I   │ ;   ┃ C   │ T   │ S   │ R   │ N   ┃ M   ┆ Ç   ┆
·     ┃     │     │     │     │ ,   ┃     │     │     │     │     ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆ Ê   ┃ À   │ È   │ X   │ :   │ W   ┃ ?   │ G   │ Q   │ H   │ F   ┃           ·
┆     ┃     │     │     │ .   │     ┃ ’   │     │     │     │     ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

altgr = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆   ¶ ┃   „ │   “ │   ” │   ≤ │   ≥ ┃   ^ │   ¬ │   ¼ │   ½ │   ¾ ┃   ′ ┆   ″ ┆
┆   – ┃   — │   < │   > │   [ │   ] ┃   _ │   ± │   − │   ÷ │   × ┃   ≠ ┆   ‰ ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃   ¦ │   ő │     │   § │     ┃     │     │     │   ø │     ┃     ┆     ┆
·     ┃   | │   ó │   œ │   { │   } ┃   ¡ │   ǒ │   ð │   £ │   ĳ ┃   ~ ┆   ə ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃     │     │   ¤ │   ȯ │   ơ ┃   ſ │     │   ẞ │   ™ │     ┃   º ┆   ț ┆
·     ┃   æ │   ù │   € │   ö │   ' ┃   © │   þ │   ß │   ® │   õ ┃   ō ┆   ţ ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆     ┃     │  *, │     │   · │   ‘ ┃   ỏ │     │   ̣ọ │   ‡ │   ª ┃           ·
┆   / ┃   \ │   ò │   & │   … │   ŏ ┃   ¿ │   µ │   å │   † │   ǫ ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

[spacebar]
shift       = "\u202f"  # NARROW NO-BREAK SPACE
altgr       = "\u005f"  # LOW LINE
altgr_shift = "\u00a0"  # NO-BREAK SPACE
