name        = "HyperTexte v1.1.2 1DFH" 
name8       = "hyper_1dk"         # short Windows filename: no spaces, no special chars
locale      = "fr"
variant     = "1DK"
author      = "Adrien MOYAUX"
description = "Disposition HyperTexte, pour une saisie plus rapide de texte."
url         = "https://hypertexte.beseven.fr"
version     = "1.1.2"
geometry    = "ISO"

base = '''
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┲━━━━━━━━━━┓
│     │     │     │     │     │     │     │     │     │     │     │     │     ┃          ┃
│     │ 1   │ 2   │ 3   │ 4   │ 5   │ 6   │ 7   │ 8   │ 9   │ 0   │ €   │     ┃ ⌫       ┃
┢━━━━━┷━━┱──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┺━━┳━━━━━━━┫
┃        ┃ Z   │ Y   │ O   │ W   │ B   │ F   │ D   │ L   │ P   │ ?   │     │     ┃       ┃
┃ ↹      ┃   á │   í │     │     │     │    │     │    û │   q │ ’   │     │     ┃       ┃
┣━━━━━━━━┻┱────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┺┓  ⏎   ┃
┃         ┃ A   │ I   │ E   │ U   │ K   │ V   │ S   │ N   │ T   │ R   │     │     ┃      ┃
┃ ⇬       ┃   è │   é │   œ │     │     │     │     │   ô │     │     │     │     ┃      ┃
┣━━━━━━┳━━┹──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┲━━┷━━━━━┻━━━━━━┫
┃      ┃     │ :   │ J   │ À   │*¨   │ ;   │ M   │ C   │ H   │ G   │ X   ┃               ┃
┃ ⇧    ┃     │ . ù │   æ │   ê │***¨ │ ,   │   ñ │   ç │   î │     │   â ┃ ⇧             ┃
┣━━━━━━┻┳━━━━┷━━┳━━┷━━━━┱┴─────┴─────┴─────┴─────┴─────┴─┲━━━┷━━━┳━┷━━━━━╋━━━━━━━┳━━━━━━━┫
┃       ┃       ┃       ┃                                ┃       ┃       ┃       ┃       ┃
┃ Ctrl  ┃ super ┃ Alt   ┃ ␣                              ┃ AltGr ┃ super ┃ menu  ┃ Ctrl  ┃
┗━━━━━━━┻━━━━━━━┻━━━━━━━┹────────────────────────────────┺━━━━━━━┻━━━━━━━┻━━━━━━━┻━━━━━━━┛
'''

altgr = '''
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┲━━━━━━━━━━┓
│     │     │     │     │     │     │     │     │     │     │     │     │     ┃          ┃
│     │ 1   │ 2   │ 3   │ 4   │ 5   │ 6   │ 7   │ 8   │ 9   │ 0   │ €   │     ┃ ⌫       ┃
┢━━━━━┷━━┱──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┺━━┳━━━━━━━┫
┃        ┃   „ │   „ │     │     │   “ │   ” │   § │   ≠ │   ± │     │     │     ┃       ┃
┃ ↹      ┃   ` │   @ │   % │   ! │   « │   » │   $ │   = │   + │   ' │     │     ┃       ┃
┣━━━━━━━━┻┱────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┺┓  ⏎   ┃
┃         ┃   ⩽ │   ⩾ │    │     │     │   ¦ │     │     │     │     │     │     ┃      ┃
┃ ⇬       ┃   < │   > │   { │   } │   \ │   | │   ( │   ) │   [ │   ] │     │     ┃      ┃
┣━━━━━━┳━━┹──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┲━━┷━━━━━┻━━━━━━┫
┃      ┃     │   … │     │     │     │   · │     │     │     │     │   × ┃               ┃
┃ ⇧    ┃     │   : │   / │   = │   " │   ; │   & │   ^ │   # │   ~ │   * ┃ ⇧             ┃
┣━━━━━━┻┳━━━━┷━━┳━━┷━━━━┱┴─────┴─────┴─────┴─────┴─────┴─┲━━━┷━━━┳━┷━━━━━╋━━━━━━━┳━━━━━━━┫
┃       ┃       ┃       ┃                                ┃       ┃       ┃       ┃       ┃
┃ Ctrl  ┃ super ┃ Alt   ┃ ␣                              ┃ AltGr ┃ super ┃ menu  ┃ Ctrl  ┃
┗━━━━━━━┻━━━━━━━┻━━━━━━━┹────────────────────────────────┺━━━━━━━┻━━━━━━━┻━━━━━━━┻━━━━━━━┛
'''


[spacebar]
shift       = "-"
altgr       = "_"
1dk         = "\u00a0"  # NO-BREAK SPACE
1dk_shift   = "\u202f"  # NARROW NO-BREAK SPACE
altgr_shift = " " 
