name        = "Optergol"
name8       = "optergol"
locale      = "fr"
variant     = "optergol"
description = "French (Optimot + Ergol 1dk)"
author      = "Auk_Bear"
url         = ""
geometry    = "ERGO"
version     = "0.2"

base = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆ ~   ┃ € ‚ │ « ‘ │ » ’ │ $   │ %   ┃ ^   │ &   │ *   │ #   │ @   ┃ _ – ┆ + ± ┆
┆ `   ┃ 1 „ │ 2 “ │ 3 ” │ 4 ¢ │ 5 ‰ ┃ 6 ¥ │ 7 ¤ │ 8 € │ 9 § │ 0 ° ┃ / ÷ ┆ = ≠ ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ K   │ Y   │ O   │ P   │ W*/ ┃ :   │ D ‡ │ L ‖ │***¨ │ Q ⁕ ┃ [   ┆ ]   ┆
·     ┃   â │   è │   ô │   œ │  */ ┃ . · │   † │   § │***¨ │   ¶ ┃ (   ┆ )   ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ A   │ I   │ E   │ U   │ B*˚ ┃ F   │ T ‑ │ S   │ R   │ N   ┃ "   ┆ |   ┆
·     ┃   à │   é │   û │   ù │   ° ┃   … │   - │   – │   — │   _ ┃ '   ┆ \   ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆ X   │ J   │ Z   │ C   │ V*ˇ │ ”   ┃ ;*¸ │ G   │ M ˄ │ H ˂ │ X ◦ ┃           ·
┆   æ │   ê │     │   ç │  *ˇ │ “ „ ┃ ,*, │  *µ │   ˅ │   ˃ │   • ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''



altgr = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆     ┃   ¹ │   ² │   ³ │   ⁴ │   ⁵ ┃   ⁶ │   ⁷ │   ⁸ │   ⁹ │   ⁰ ┃     ┆     ┆
┆     ┃   ₁ │   ₂ │   ₃ │   ₄ │   ₅ ┃   ₆ │   ₇ │   ₈ │   ₉ │   ₀ ┃     ┆     ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃  *^ │   ≤ │   ≥ │  *¤ │   ‰ ┃     │   × │  *` │     │  *´ ┃     ┆     ┆
·     ┃   ^ │   < │   > │   $ │   % ┃   & │   * │   ` │   @ │   ' ┃     ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃     │   « │   » │     │   ? ┃   ! │  */ │   ± │   — │   ÷ ┃     ┆     ┆
·     ┃   { │   ( │   ) │   } │   ? ┃   ! │   \ │   + │   - │   / ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆  *~ │     │     │     │     │     ┃  *¸ │   ¦ │     │     │   ≠ ┃           ·
┆   ~ │   [ │   ] │   _ │   # │   " ┃   ; │   | │   : │   . │   = ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

[spacebar]
shift       = "\u202f"  # NARROW NO-BREAK SPACE
altgr       = "\u0020"  # SPACE
altgr_shift = "\u00a0"  # NO-BREAK SPACE
1dk         = "\u0027"  # RIGHT SINGLE QUOTATION MARK
1dk_shift   = "\u23B5"  # BOTTOM BRACKET
