# baseURL = "https://ergol.org"
relativeURLs = false  # our 404 page does not support relative URLs
languageCode = "fr"
title = "Ergo‑L"

[params]
subtitle = "Ergonomie optimisée pour le français, l’anglais, le code."
description = "Une disposition de clavier ergonomique de type Colemak, optimisée pour le français, l’anglais et le code."

[security.exec]
allow = ["pandoc"]

[markup]
defaultMarkdownHandler = "pandoc"

[taxonomies]
tag = "tags"
author = "authors"
# category = "categories"

[module]
    [[module.mounts]]
        source = "../code"
        target = "assets/js"
    [[module.mounts]]
        source = "assets"
        target = "assets"
    [[module.mounts]]
        source = "../corpus"
        target = "static/corpus"
    [[module.mounts]]
        source = "../layouts"
        target = "static/layouts"
    [[module.mounts]]
        source = "static"
        target = "static"

[menus]
    [[menus.main]]
        name    = "Ergo‑L"
        pageRef = "/"
        weight  = 1
    # [[menus.main]]
    #     name    = "Installer"
    #     pageRef = "/lts"
    #     parent  = "Ergo‑L"
    [[menus.main]]
        name    = "Alternatives"
        pageRef = "/comparatif"
        weight  = 2
    [[menus.main]]
        name    = "Bépo ?"
        pageRef = "/bepo"
        parent  = "Alternatives"
    [[menus.main]]
        name    = "Erglace !"
        pageRef = "/erglace"
        parent  = "Alternatives"
    [[menus.main]]
        name    = "Lafayette *"
        pageRef = "/lafayette"
        parent  = "Alternatives"
    [[menus.main]]
        name    = "Analyseur"
        pageRef = "/stats"
        weight  = 3
    [[menus.main]]
        name    = "Lexique"
        pageRef = "/lexique"
        weight  = 4
    [[menus.main]]
        name    = "Apprendre"
        pageRef = "/dactylo"
        weight  = 5
