# baseURL = "https://ergol.org"
relativeURLs = true
languageCode = "fr"
title = "Ergo‑L"

[params]
subtitle = "Ergonomie optimisée pour le français, l’anglais, le code."
description = "Une disposition de clavier ergonomique de type Colemak, optimisée pour le français, l’anglais et le code."

[security.exec]
allow = ["pandoc"]

[markup]
defaultMarkdownHandler = "pandoc"

[module]
    [[module.mounts]]
        source = "../code"
        target = "assets/js"
    [[module.mounts]]
        source = "assets"
        target = "assets"
    [[module.mounts]]
        source = "../corpus"
        target = "static/corpus"
    [[module.mounts]]
        source = "../layouts"
        target = "static/layouts"
    [[module.mounts]]
        source = "static"
        target = "static"
